{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.iukr",
    "module": "logging-starter",
    "version": "1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.1-SNAPSHOT.jar",
          "url": "logging-starter-1.1-SNAPSHOT.jar",
          "size": 14607,
          "sha512": "a6181d4004ec5db0dd6fe87f9089af84f30d679268c7c302732b72f55f52c1ac157600cf19d0988166749445d88ac98973b26f3ffe9fb06cd45b0629068f3a56",
          "sha256": "3d0de2c4f133c9ae31ba5e03492e6de909eb5ab392b0dee81ca9c5dfba4effbd",
          "sha1": "5b5e91ed542b62eb93c9518f211a300c16cffa68",
          "md5": "28f1660583db8bb56a9167ecbb2efdfe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.1-SNAPSHOT.jar",
          "url": "logging-starter-1.1-SNAPSHOT.jar",
          "size": 14607,
          "sha512": "a6181d4004ec5db0dd6fe87f9089af84f30d679268c7c302732b72f55f52c1ac157600cf19d0988166749445d88ac98973b26f3ffe9fb06cd45b0629068f3a56",
          "sha256": "3d0de2c4f133c9ae31ba5e03492e6de909eb5ab392b0dee81ca9c5dfba4effbd",
          "sha1": "5b5e91ed542b62eb93c9518f211a300c16cffa68",
          "md5": "28f1660583db8bb56a9167ecbb2efdfe"
        }
      ]
    }
  ]
}
